'use client';
import {useEffect,useState} from 'react';
import {Truck,RefreshCw} from 'lucide-react';
import {money} from '@/lib/quote';
export function FreightDiagnostics({value}:{value?:{stage:string;status?:number;rayId?:string;time:string}}){return value?<p className="freight-diagnostics">Step: {value.stage}{value.status?' · HTTP '+value.status:''}{value.rayId?' · Cloudflare Ray ID: '+value.rayId:''}<br/>{value.time}</p>:null;}
export default function MagentoFreightConnection(){
 const [settings,setSettings]=useState<{storeCode:string;enabled:boolean;testedAt?:string;testAmount?:number}|null>(null),[storeCode,setStoreCode]=useState('default'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[diagnostics,setDiagnostics]=useState<any>();
 async function load(){setError('');try{const r=await fetch('/api/admin/magento-freight',{cache:'no-store'}),data:any=await r.json();if(!r.ok)throw Error(data.error);setSettings(data);setStoreCode(data.storeCode);}catch{setError('Magento settings could not be loaded.');}}
 useEffect(()=>{void load();},[]);
 async function run(action:'test'|'disconnect'){setBusy(true);setError('');setMessage('');setDiagnostics(undefined);try{const r=await fetch('/api/admin/magento-freight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,storeCode}),cache:'no-store'}),data:any=await r.json();if(!r.ok){setDiagnostics(data.diagnostics);throw Error(data.error||'Magento could not be reached.');}if(action==='test'){setSettings(data);setMessage('Connection enabled. Delivery: '+money(data.testAmount)+' ex GST. '+(data.matchesExample?'Matches your $81.82 example.':'This differs from your $81.82 example. Check current Magento rates before quoting.'));}else{setSettings(prev=>prev&&({...prev,enabled:false}));setMessage('Automatic freight disconnected. Existing quotes and manual freight are retained.');}}catch(e){setError(e instanceof Error?e.message:'Connection failed.');}finally{setBusy(false);}}
 return <section className="card connection-settings-card"><div className="connection-card-heading"><Truck/><div><h2>Magento Freight</h2><p>Use Magento’s cubic freight calculation</p></div><span className={'connection-badge '+(settings?.enabled?'connected':'')}>{settings?.enabled?'Enabled':'Not enabled'}</span></div>
 <p className="connection-refresh-mode"><RefreshCw size={16}/> On demand — fresh rates each time you calculate freight.</p><label className="field"><span>Magento website</span><input readOnly value="https://www.verdex.com.au"/></label><label className="field"><span>Store code</span><input value={storeCode} maxLength={64} disabled={busy} onChange={e=>setStoreCode(e.target.value)}/></label>
 <p className="connection-help">Test V4020 × 1 to New South Wales 2121. Expected delivery: $81.82 ex GST. A successful test saves and enables this connection. No order or payment is created.</p>
 <div className="actions"><button className="btn primary" disabled={busy||!settings||!storeCode.trim()} onClick={()=>void run('test')}><RefreshCw size={16}/>{busy?'Working…':settings?.enabled?'Test connection & save':'Test & enable connection'}</button>{settings?.enabled&&<button className="btn outline" disabled={busy} onClick={()=>void run('disconnect')}>Disconnect</button>}{!settings&&error&&<button className="btn outline" onClick={()=>void load()}>Reload settings</button>}</div>
 {settings?.testedAt&&<p className="connection-help">Last successful test: {new Date(settings.testedAt).toLocaleString('en-AU')}{settings.testAmount!==undefined?' · '+money(settings.testAmount)+' ex GST':''}</p>}
 {message&&<p className="connection-feedback success" role="status">{message}</p>}{error&&<p className="connection-feedback error" role="alert">{error}</p>}<FreightDiagnostics value={diagnostics}/>
 </section>;
}
