'use client';
import {useEffect,useState} from 'react';
import {CreditCard,PlugZap,CheckCircle2} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
type Status={configured:boolean;mode:'sandbox'|'live';verifiedAt:string|null;paymentsEnabled:boolean;secureStorageReady?:boolean};
async function api(body?:unknown){const r=await fetch('/api/admin/paypal',{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data:any=await r.json();if(!r.ok)throw Error(data.error||'PayPal could not be reached.');return data;}
export default function PaypalConnection(){
 const [status,setStatus]=useState<Status|null>(null),[mode,setMode]=useState<'sandbox'|'live'>('sandbox'),[clientId,setClientId]=useState(''),[clientSecret,setClientSecret]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false;api().then(data=>{if(!cancelled){setStatus(data);setMode(data.mode);}}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[]);
 async function run(action:'connect'|'test'|'disconnect'){
  if(busy)return;setBusy(true);setNotice('');setError('');
  const payload=action==='connect'?{action,mode,clientId,clientSecret}:{action};
  if(action==='connect'){setClientId('');setClientSecret('');}
  try{const data=await api(payload);if(action!=='test'){setStatus(data);setMode(data.mode);}setNotice(data.message);}catch(e){setError(e instanceof Error?e.message:'Unable to update PayPal.');}finally{setBusy(false);}
 }
 return <section className="card connection-settings-card"><div className="connection-card-heading"><CreditCard/><div><h2>PayPal payments</h2><p>REST API connection for quote checkout</p></div><span className={'connection-badge '+(status?.configured?'connected':'')}>{loading?'Loading…':status?.configured?(status.mode==='live'?'Live credentials saved':'Test credentials saved'):'Not connected'}</span></div>
 <form onSubmit={e=>{e.preventDefault();void run('connect');}}>
 <label className="field"><span>Connection mode</span><Select value={mode} disabled={loading||busy} onValueChange={v=>setMode(v as 'sandbox'|'live')}><SelectTrigger aria-label="PayPal connection mode"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="sandbox">Test (Sandbox)</SelectItem><SelectItem value="live">Live (Production)</SelectItem></SelectContent></Select></label>
 <label className="field"><span>{status?.configured?'Replacement Client ID':'Client ID'}</span><input type="password" autoComplete="new-password" spellCheck={false} autoCapitalize="none" value={clientId} onChange={e=>setClientId(e.target.value)} maxLength={500} required disabled={loading||busy} placeholder="Paste your PayPal REST app Client ID"/></label>
 <label className="field"><span>{status?.configured?'Replacement Client Secret':'Client Secret'}</span><input type="password" autoComplete="new-password" spellCheck={false} autoCapitalize="none" value={clientSecret} onChange={e=>setClientSecret(e.target.value)} maxLength={500} required disabled={loading||busy} placeholder="Paste your PayPal REST app Client Secret"/></label>
 <p className="connection-help">Use the Client ID and Client Secret from Apps & Credentials in the PayPal Developer Dashboard. Sandbox and Live use different credentials. Your PayPal login password and legacy API signature are not used. Credentials are encrypted and never displayed again.</p>
 {status?.configured&&<p className="connection-help">Saved mode: <strong>{status.mode==='live'?'Live':'Test (Sandbox)'}</strong>. Enter both credentials to change the saved connection. A failed connection test keeps the existing settings.</p>}
 <div className="actions"><button type="submit" className="btn primary" disabled={loading||busy||clientId.trim().length<10||!clientSecret||status?.secureStorageReady===false}><PlugZap size={16}/>{busy?'Working…':'Verify & save connection'}</button>{status?.configured&&<><button type="button" className="btn outline" disabled={busy||loading} onClick={()=>void run('test')}><CheckCircle2 size={16}/>Test saved connection</button><button type="button" className="btn outline" disabled={busy||loading} onClick={()=>void run('disconnect')}>Disconnect</button></>}</div>
 </form>{status?.verifiedAt&&<p className="connection-help">Verified when saved: {new Date(status.verifiedAt).toLocaleString('en-AU',{timeZone:'Australia/Sydney'})} (Sydney)</p>}
 <p className="connection-help">Verify & save checks your PayPal app credentials without creating an order or taking a payment. PayPal checkout payments are not enabled by saving this connection.</p>
 <details className="paypal-setup-help"><summary>How to get your PayPal credentials</summary><ol><li>Sign in to the <a href="https://developer.paypal.com/dashboard/" target="_blank" rel="noopener noreferrer">PayPal Developer Dashboard</a> using your PayPal Business account.</li><li>Open <strong>Apps &amp; Credentials</strong> and choose <strong>Sandbox</strong> for testing, or <strong>Live</strong> for production.</li><li>Select <strong>Create App</strong>, name it <strong>Verdex Quotes</strong>, and use your business / merchant account. For Sandbox, select a Sandbox business account.</li><li>Copy the app’s <strong>Client ID</strong> and <strong>Client Secret</strong> into the fields above. Select the matching mode, then click <strong>Verify &amp; save connection</strong>.</li></ol><p>Use a separate app for the quoting software so your existing website’s PayPal settings stay independent. For later payment testing, find a personal buyer account under Testing Tools → Sandbox Accounts.</p><a href="https://developer.paypal.com/api/get-started/" target="_blank" rel="noopener noreferrer">PayPal setup guide ↗</a></details>
 {error&&<p className="connection-feedback error" role="alert">{error}</p>}{notice&&<p className="connection-feedback success" role="status">{notice}</p>}
 </section>;
}
