'use client';
import {GripVertical,Trash2} from 'lucide-react';
import {TableRow,TableCell} from '@/components/ui/table';
import {QuoteNoteEditor} from './quote-note';
import type {NoteNode,QuoteBlock} from '@/lib/quote-layout';
export default function QuoteLayoutRow({block,index,columns,disabled,dragging,dropPosition,onDrag,onEnd,onMove,onDrop,onTarget,onChange,onRemove}:{block:QuoteBlock;index:number;columns:number;disabled:boolean;dragging:boolean;dropPosition?:string;onDrag:()=>void;onEnd:()=>void;onMove:(direction:number)=>void;onDrop:(position:'before'|'after')=>void;onTarget:(position:'before'|'after')=>void;onChange:(content:NoteNode[])=>void;onRemove:()=>void}){
 const label=block.kind==='divider'?'Divider':'Note';
 return <TableRow id={'quote-block-'+block.id} className={'quote-layout-row '+(dragging?'dragging-row ':'')+(dropPosition?'drop-'+dropPosition:'')} onDragOver={e=>{if(disabled)return;e.preventDefault();const rect=e.currentTarget.getBoundingClientRect();onTarget(e.clientY<rect.top+rect.height/2?'before':'after');}} onDrop={e=>{if(disabled)return;e.preventDefault();const rect=e.currentTarget.getBoundingClientRect();onDrop(e.clientY<rect.top+rect.height/2?'before':'after');}}><TableCell colSpan={columns}><div className="quote-layout-heading"><span className="quote-layout-actions"><button className="drag-handle" type="button" title="Drag to reorder" aria-label={'Reorder '+label+' '+(index+1)} disabled={disabled} draggable={!disabled} onDragStart={e=>{e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain','block:'+block.id);onDrag();}} onDragEnd={onEnd} onKeyDown={e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();onMove(e.key==='ArrowUp'?-1:1);}}}><GripVertical size={18}/></button><strong>{label}</strong></span><button type="button" className="icon-btn" aria-label={'Delete '+label+' '+(index+1)} disabled={disabled} onClick={onRemove}><Trash2 size={16}/></button></div>{block.kind==='divider'?<hr className="quote-divider"/>:<QuoteNoteEditor value={block.content} onChange={onChange} disabled={disabled} label={'Quote note '+(index+1)}/>}</TableCell></TableRow>;
}
