'use client';
import {useEffect,useState} from 'react';
import {ShieldCheck,Mail,Smartphone} from 'lucide-react';
import {InputOTP,InputOTPGroup,InputOTPSlot} from '@/components/ui/input-otp';
export default function TwoFactorChallenge({onVerified}:{onVerified:()=>void}){
 const [status,setStatus]=useState<{configured:boolean;email:string;mobile:string|null}|null>(null),[channel,setChannel]=useState<'email'|'sms'>('email'),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[cooldown,setCooldown]=useState(0);
 useEffect(()=>{fetch('/api/workspace/two-factor',{cache:'no-store'}).then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error);setStatus(d);}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(cooldown<=0)return;const timer=setTimeout(()=>setCooldown(v=>v-1),1000);return ()=>clearTimeout(timer);},[cooldown]);
 async function submit(action:'send'|'verify'){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/workspace/two-factor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='send'?{action,channel}:{action,code})}),d:any=await r.json();if(!r.ok)throw Error(d.error);if(action==='verify'){onVerified();return;}setSent(true);setCode('');setCooldown(d.retryAfter||60);setMessage(d.message);}catch(e){setError(e instanceof Error?e.message:'Verification failed.');}finally{setBusy(false);}}
 return <main className="verification-page"><section className="card verification-card"><img src="/verdex-logo.svg" alt="Verdex" width="160"/><h1><ShieldCheck size={25}/>Verify your sign-in</h1><p>Choose where to receive your verification code.</p>{status&&!status.configured?<p role="alert" className="price-warning">Email/SMS verification needs to be connected by your hosting administrator.</p>:<><div className="verification-options"><label><input type="radio" name="verification-channel" checked={channel==='email'} disabled={busy} onChange={()=>{setChannel('email');setSent(false);setCode('');}}/><Mail size={19}/><span>Email<small>{status?.email||'Loading…'}</small></span></label><label><input type="radio" name="verification-channel" checked={channel==='sms'} disabled={busy||!status?.mobile} onChange={()=>{setChannel('sms');setSent(false);setCode('');}}/><Smartphone size={19}/><span>Mobile SMS<small>{status?.mobile||'No mobile number saved'}</small></span></label></div><button className="btn outline full" disabled={busy||!status?.configured||cooldown>0} onClick={()=>void submit('send')}>{cooldown>0?'Send another code in '+cooldown+'s':sent?'Resend code':'Send code'}</button>{sent&&<form onSubmit={e=>{e.preventDefault();void submit('verify');}}><label htmlFor="verification-code">Verification code</label><InputOTP id="verification-code" autoComplete="one-time-code" inputMode="numeric" maxLength={6} pattern="^[0-9]+$" value={code} onChange={setCode} disabled={busy}><InputOTPGroup>{Array.from({length:6},(_,i)=><InputOTPSlot key={i} index={i}/>)}</InputOTPGroup></InputOTP><button className="btn primary full" disabled={busy||code.length!==6}>{busy?'Checking…':'Verify and continue'}</button></form>}</>}{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="price-warning">{error}</p>}<a href="/signout-with-chatgpt?return_to=/">Sign out</a></section></main>;
}
