'use client';
import {useEffect,useState} from 'react';
import EwayConnection from './eway-connection';
import PaypalConnection from './paypal-connection';
import MagentoFreightConnection from './magento-freight-connection';
import {Link2,Users,Table2,FileCode2,RefreshCw,CheckCircle2,PlugZap,Percent,PackagePlus} from 'lucide-react';
type Kind='hubspot'|'sheet'|'feed'|'gp'|'autoOptions'|'exo'|'approval';
async function api(path:string,body?:unknown){const response=await fetch(path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),cache:'no-store'});const data:any=await response.json();if(!response.ok)throw Error(data.error||'Unable to load connections.');return data;}
export default function WorkspaceConnections({onChanged}:{onChanged:(kind:'sheet'|'feed'|'gp'|'autoOptions'|'exo'|'approval')=>void}){
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState<Kind|null>(null),[notice,setNotice]=useState<Partial<Record<Kind,{text:string;error?:boolean}>>>({});
 const [hubspot,setHubspot]=useState<{configured:boolean;managedByHosting:boolean}|null>(null),[token,setToken]=useState('');
 const [sheet,setSheet]=useState({sheetId:'',tab:'Costs',mode:'public-sheet',refreshMinutes:15 as number|''}),[feed,setFeed]=useState({url:'',refreshMinutes:15 as number|''});
 const [exo,setExo]=useState({sheetId:'',tab:'exo',mode:'public-sheet',refreshMinutes:15 as number|''});
 const [autoLimit,setAutoLimit]=useState('20'),[savedAutoLimit,setSavedAutoLimit]=useState(20);
 const [approvalAmount,setApprovalAmount]=useState('10000'),[minimumGp,setMinimumGp]=useState('20');
 const [gpTarget,setGpTarget]=useState('40'),[savedGpTarget,setSavedGpTarget]=useState(40);
 const [saved,setSaved]=useState<{sheetId:string;tab:string;url:string}|null>(null);
 async function load(){setLoading(true);setError('');try{const [settings,status]=await Promise.all([api('/api/admin/connections'),api('/api/admin/hubspot',{action:'status'})]);setApprovalAmount(String(settings.approval.highValueCents/100));setMinimumGp(String(settings.gp.minimumSavePct));setSheet(settings.sheet);setExo(settings.exo);setFeed(settings.feed);setAutoLimit(String(settings.autoOptions.maxOptions));setSavedAutoLimit(settings.autoOptions.maxOptions);setGpTarget(String(settings.gp.targetPct));setSavedGpTarget(settings.gp.targetPct);setSaved({sheetId:settings.sheet.sheetId,tab:settings.sheet.tab,url:settings.feed.url});setHubspot(status);}catch(e){setError(e instanceof Error?e.message:'Connections could not be loaded.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function run(kind:Kind,work:()=>Promise<string>){setBusy(kind);setNotice(prev=>({...prev,[kind]:undefined}));try{const text=await work();setNotice(prev=>({...prev,[kind]:{text}}));}catch(e){setNotice(prev=>({...prev,[kind]:{text:e instanceof Error?e.message:'Please try again.',error:true}}));}finally{setBusy(null);}}
 function sourceAction(kind:'sheet'|'feed'|'exo'|'approval',action:'save'|'test'|'refresh'){void run(kind,async()=>{const data=await api('/api/admin/connections',{kind,action,settings:kind==='sheet'?sheet:kind==='exo'?exo:feed});if(action==='save'){if(kind==='exo'){setExo(data.settings);}else if(kind==='sheet'){setSheet(data.settings);setSaved(prev=>prev&&({...prev,sheetId:data.settings.sheetId,tab:data.settings.tab}));}else{setFeed(data.settings);setSaved(prev=>prev&&({...prev,url:data.settings.url}));}}if(action!=='test')onChanged(kind);return data.message+' '+data.count.toLocaleString()+(kind==='sheet'?' SKU rows.':' products.')+(data.skipped?' '+data.skipped+' invalid or duplicate rows skipped.':'');});}
 function message(kind:Kind){const item=notice[kind];return item?<p className={'connection-feedback '+(item.error?'error':'success')} role={item.error?'alert':'status'}>{item.text}</p>:null;}
 return <main className="page-shell connections-page"><div className="connections-title"><div><div className="eyebrow dark">SALES WORKSPACE</div><h1>Workspace connections</h1><p>Manage the sources used for customers, product costs, your catalogue and freight, plus GP and automatic options settings.</p></div><Link2 size={28}/></div>
 {loading?<p role="status">Loading connections…</p>:error?<div className="card connection-settings-card"><p role="alert">{error}</p><button className="btn outline" onClick={()=>void load()}>Try again</button></div>:<div className="connections-grid">
  <section className="card connection-settings-card"><div className="connection-card-heading"><Users/><div><h2>HubSpot</h2><p>Contacts, linked companies and vendor numbers</p></div><span className={'connection-badge '+(hubspot?.configured?'connected':'')}>{hubspot?.configured?'Configured':'Not connected'}</span></div>
   <p className="connection-refresh-mode"><RefreshCw size={16}/> On demand — refreshed when you search for a contact.</p>{hubspot?.managedByHosting?<p>The access token is managed in hosting settings.</p>:<form onSubmit={e=>{e.preventDefault();const entered=token;setToken('');void run('hubspot',async()=>{await api('/api/admin/hubspot',{action:'connect',token:entered});setHubspot({configured:true,managedByHosting:false});return 'HubSpot connected. Contact and company access verified.';});}}><label className="field"><span>{hubspot?.configured?'Replace access token':'Access token'}</span><input type="password" autoComplete="off" spellCheck={false} value={token} maxLength={1000} disabled={!!busy} onChange={e=>setToken(e.target.value)} placeholder={hubspot?.configured?'Enter a new token to replace the saved connection':'Paste your private-app access token'}/></label><p className="connection-help">Use the Access token only. The token is encrypted and is never shown again.</p><button type="submit" className="btn primary" disabled={!!busy||token.trim().length<20}><PlugZap size={16}/>{busy==='hubspot'?'Working…':hubspot?.configured?'Update connection':'Connect HubSpot'}</button></form>}
   {hubspot?.configured&&<div className="actions"><button className="btn outline" disabled={!!busy} onClick={()=>void run('hubspot',async()=>{await api('/api/admin/hubspot',{action:'test'});return 'HubSpot connection verified. Contacts and companies are accessible.';})}><CheckCircle2 size={16}/>Test connection</button>{!hubspot.managedByHosting&&<button className="btn outline" disabled={!!busy} onClick={()=>void run('hubspot',async()=>{await api('/api/admin/hubspot',{action:'disconnect'});setHubspot({configured:false,managedByHosting:false});setToken('');return 'HubSpot disconnected. Saved quotes have been retained.';})}>Disconnect</button>}</div>}{message('hubspot')}
  </section>
  <section className="card connection-settings-card"><div className="connection-card-heading"><Table2/><div><h2>Google Sheet</h2><p>MYOB EXO costs and stock by location</p></div><span className={'connection-badge '+(saved?.sheetId?'connected':'')}>{saved?.sheetId?'Configured':'Not connected'}</span></div>
   <form onSubmit={e=>{e.preventDefault();sourceAction('sheet','save');}}><label className="field"><span>Spreadsheet ID or Google Sheets link</span><input value={sheet.sheetId} onChange={e=>setSheet({...sheet,sheetId:e.target.value})} disabled={!!busy} maxLength={500}/></label><label className="field"><span>Sheet / tab name</span><input value={sheet.tab} onChange={e=>setSheet({...sheet,tab:e.target.value})} disabled={!!busy} maxLength={100}/></label><div className="connection-refresh-control"><RefreshCw size={19} aria-hidden="true"/><label className="field"><span>Refresh interval (minutes)</span><input type="number" inputMode="numeric" min="1" max="1440" step="1" required value={sheet.refreshMinutes} disabled={!!busy} onChange={e=>setSheet({...sheet,refreshMinutes:e.target.value===''?'':Number(e.target.value)})}/></label><p>Fetch fresh data on the next request after this interval. Use Refresh saved source to update immediately.</p></div><p className="connection-help">The sheet must allow “Anyone with the link → Viewer”. Required columns: SKU and Average Cost. Stock columns: Total Stock, Committed (or COMMITTED STOCK), Melbourne, Brisbane and Sydney.</p><div className="actions"><button className="btn primary" disabled={!!busy||!sheet.sheetId.trim()||!sheet.tab.trim()}>{busy==='sheet'?'Working…':'Save connection'}</button><button type="button" className="btn outline" disabled={!!busy||!sheet.sheetId.trim()} onClick={()=>sourceAction('sheet','test')}>Test connection</button><button type="button" className="btn outline" disabled={!!busy||!saved?.sheetId} onClick={()=>sourceAction('sheet','refresh')}><RefreshCw size={16}/>Refresh saved source</button></div></form>{message('sheet')}
  </section>
  <section className="card connection-settings-card"><div className="connection-card-heading"><Table2/><div><h2>EXO product feed</h2><p>Products from your EXO ERP Google Sheet tab</p></div><span className={'connection-badge '+(exo.sheetId?'connected':'')}>{exo.sheetId?'Configured':'Not connected'}</span></div>
   <form onSubmit={e=>{e.preventDefault();sourceAction('exo','save');}}><label className="field"><span>Spreadsheet ID or Google Sheets link</span><input value={exo.sheetId} onChange={e=>setExo({...exo,sheetId:e.target.value})} disabled={!!busy} maxLength={500}/></label><label className="field"><span>Sheet / tab name</span><input value={exo.tab} onChange={e=>setExo({...exo,tab:e.target.value})} disabled={!!busy} maxLength={100}/></label><div className="connection-refresh-control"><RefreshCw size={19} aria-hidden="true"/><label className="field"><span>Refresh interval (minutes)</span><input type="number" inputMode="numeric" min="1" max="1440" step="1" required value={exo.refreshMinutes} disabled={!!busy} onChange={e=>setExo({...exo,refreshMinutes:e.target.value===''?'':Number(e.target.value)})}/></label><p>Fetch fresh data on the next request after this interval. Use Refresh saved source to update immediately.</p></div><p className="connection-help">The sheet must allow “Anyone with the link → Viewer”. Required columns: SKU, Description and Sell Price. Optional: Sales HTML. Sell prices are imported excluding GST.</p><div className="actions"><button className="btn primary" disabled={!!busy||!exo.sheetId.trim()||!exo.tab.trim()}>{busy==='exo'?'Working…':'Save connection'}</button><button type="button" className="btn outline" disabled={!!busy||!exo.sheetId.trim()} onClick={()=>sourceAction('exo','test')}>Test connection</button><button type="button" className="btn outline" disabled={!!busy||!exo.sheetId} onClick={()=>sourceAction('exo','refresh')}><RefreshCw size={16}/>Refresh saved source</button></div></form>{message('exo')}
  </section>
  <section className="card connection-settings-card"><div className="connection-card-heading"><FileCode2/><div><h2>Magento XML feed</h2><p>Products, images, descriptions and sale prices</p></div><span className="connection-badge connected">Configured</span></div>
   <form onSubmit={e=>{e.preventDefault();sourceAction('feed','save');}}><label className="field"><span>Product feed URL</span><input type="url" value={feed.url} onChange={e=>setFeed({...feed,url:e.target.value})} disabled={!!busy} maxLength={500}/></label><div className="connection-refresh-control"><RefreshCw size={19} aria-hidden="true"/><label className="field"><span>Refresh interval (minutes)</span><input type="number" inputMode="numeric" min="1" max="1440" step="1" required value={feed.refreshMinutes} disabled={!!busy} onChange={e=>setFeed({...feed,refreshMinutes:e.target.value===''?'':Number(e.target.value)})}/></label><p>Fetch fresh data on the next request after this interval. Use Refresh saved source to update immediately.</p></div><p className="connection-help">Use a public HTTPS XML feed under verdex.com.au/media/. Product prices are imported excluding GST.</p><div className="actions"><button className="btn primary" disabled={!!busy||!feed.url.trim()}>{busy==='feed'?'Working…':'Save connection'}</button><button type="button" className="btn outline" disabled={!!busy||!feed.url.trim()} onClick={()=>sourceAction('feed','test')}>Test connection</button><button type="button" className="btn outline" disabled={!!busy} onClick={()=>sourceAction('feed','refresh')}><RefreshCw size={16}/>Refresh saved source</button></div></form>{message('feed')}
  </section>
 <section className="card connection-settings-card"><div className="connection-card-heading"><PackagePlus/><div><h2>Automatic additional options</h2><p>Related and other SKU suggestions from the product feed</p></div><span className="connection-badge">Current: {savedAutoLimit}</span></div>
 <form onSubmit={e=>{e.preventDefault();if(!autoLimit.trim())return;void run('autoOptions',async()=>{const data=await api('/api/admin/connections',{kind:'autoOptions',action:'save',settings:{maxOptions:Number(autoLimit)}});setAutoLimit(String(data.settings.maxOptions));setSavedAutoLimit(data.settings.maxOptions);onChanged('autoOptions');return 'Automatic options limit saved at '+data.settings.maxOptions+' per quote.';});}}>
 <label className="field"><span>Maximum automatic options per quote</span><input className="workspace-number-input" type="number" min="0" max="50" step="1" required inputMode="numeric" value={autoLimit} onChange={e=>setAutoLimit(e.target.value)} disabled={!!busy}/></label>
 <p className="connection-help">Default: 20. Set to 0 to turn automatic suggestions off. Manually added products and optional items do not count towards this limit and always keep their place. Automatic suggestions are trimmed to fit the remaining space within the 50-line quote limit. Applies when editing and saving drafts; approved quotes keep their saved options until revised.</p>
 <button className="btn primary" type="submit" disabled={!!busy||!autoLimit.trim()||!Number.isInteger(Number(autoLimit))||Number(autoLimit)<0||Number(autoLimit)>50}>{busy==='autoOptions'?'Saving…':'Save options limit'}</button>
 </form>{message('autoOptions')}</section>
 <section className="card connection-settings-card"><div className="connection-card-heading"><CheckCircle2/><div><h2>High-value quote approval</h2><p>Require Administrator / approver approval</p></div></div><form onSubmit={e=>{e.preventDefault();void run('approval',async()=>{const data=await api('/api/admin/connections',{kind:'approval',action:'save',settings:{highValueCents:Math.round(Number(approvalAmount)*100)}});setApprovalAmount(String(data.settings.highValueCents/100));onChanged('approval');return data.message;});}}><label className="field"><span>Approval required above (AUD, including GST)</span><input className="workspace-number-input" type="number" min="0" max="100000000" step="0.01" required value={approvalAmount} disabled={!!busy} onChange={e=>setApprovalAmount(e.target.value)}/></label><p className="connection-help">Uses the total after discounts, including freight, handling and GST. Sales users can save a draft and request approval; an Administrator/approver must approve before customer acceptance.</p><button className="btn primary" disabled={!!busy}>{busy==='approval'?'Saving…':'Save approval limit'}</button></form>{message('approval')}</section>
 <MagentoFreightConnection/>
 <EwayConnection/>
 <PaypalConnection/>
 <section className="card connection-settings-card gp-settings-card"><div className="connection-card-heading"><Percent/><div><h2>GP target</h2><p>Orange warnings for product lines and the overall quote</p></div><span className="connection-badge">Current: {savedGpTarget}%</span></div>
 <form onSubmit={e=>{e.preventDefault();if(!gpTarget.trim())return;void run('gp',async()=>{const data=await api('/api/admin/connections',{kind:'gp',action:'save',settings:{targetPct:Number(gpTarget),minimumSavePct:Number(minimumGp)}});setGpTarget(String(data.settings.targetPct));setSavedGpTarget(data.settings.targetPct);onChanged('gp');return 'GP target saved at '+data.settings.targetPct+'%. Quote warnings will use this target.';});}}>
 <label className="field"><span>GP target (%)</span><input className="workspace-number-input" type="number" min="0" max="100" step="0.1" required inputMode="decimal" value={gpTarget} onChange={e=>setGpTarget(e.target.value)} disabled={!!busy}/></label>
 <label className="field"><span>Minimum GP to save without approval (%)</span><input className="workspace-number-input" type="number" min="0" max="100" step="0.1" required value={minimumGp} disabled={!!busy} onChange={e=>setMinimumGp(e.target.value)}/></label><p className="connection-help">Lines below this minimum turn red. Only an Administrator/approver or Super Administrator can save them. GP is calculated after discounts. If GP is unavailable, Administrator approval is required before releasing the quote.</p>
 <p className="connection-help">Product lines and the overall product GP are flagged orange when below this percentage. Applies across the workspace. Prices and costs stay the same.</p>
 <button className="btn primary" type="submit" disabled={!!busy||!gpTarget.trim()||!Number.isFinite(Number(gpTarget))||Number(gpTarget)<0||Number(gpTarget)>100}>{busy==='gp'?'Saving…':'Save GP target'}</button>
 </form>{message('gp')}</section>
 </div>}
 </main>;
}
