import {type Quote,totals,money,dateLabel} from './quote';
// Small dependency-free PDF writer for the Worker runtime. Text uses standard Helvetica.
function ascii(s:string){return s.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[–—]/g,'-').replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/[^\x20-\x7e\n]/g,'?');}
const esc=(s:string)=>ascii(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
function wrap(s:string,n=90){return ascii(s).split('\n').flatMap(para=>{const a:string[]=[];let line='';for(const word of para.split(/\s+/)){if((line+' '+word).length>n&&line){a.push(line);line='';}if(word.length>n){if(line)a.push(line);for(let j=0;j<word.length;j+=n)a.push(word.slice(j,j+n));line='';}else line+=(line?' ':'')+word;}a.push(line);return a;});}
export function quotePdf(q:Quote,url:string):Uint8Array{
const pages:{commands:string;linkY?:number}[]=[];let commands='',y=718;
function text(s:string,x:number,at:number,size=10,bold=false,color='0.13 0.23 0.31'){commands+=`BT /${bold?'F2':'F1'} ${size} Tf ${color} rg 1 0 0 1 ${x} ${at} Tm (${esc(s)}) Tj ET\n`;}
function start(){commands='';y=718;commands+='0.025 0.36 0.61 rg 0 758 595 84 re f\n';text('VERDEX',42,789,26,true,'1 1 1');text('QUOTATION',412,796,13,true,'1 1 1');text(q.number+' / Rev '+q.revision,412,778,9,false,'0.8 0.91 1');text('TEST QUOTATION - No live order or payment',42,736,9,true,'0.34 0.48 0.58');}
function finish(linkY?:number){text('Verdex Equipment Pty Ltd  |  (02) 8866 4600  |  daniel@verdex.com.au',42,34,8,false,'0.45 0.55 0.62');text('Page '+(pages.length+1),514,34,8);pages.push({commands,linkY});}
function room(h:number){if(y-h<66){finish();start();}}
function line(s:string,size=10,bold=false){for(const l of wrap(s,size>=14?55:92)){room(size+9);text(l,42,y,size,bold);y-=size+7;}}
function rule(){commands+=`0.82 0.88 0.92 RG 42 ${y} m 553 ${y} l S\n`;y-=20;}
start();line(q.company,18,true);line(q.contact+' | '+q.email);line(q.address);y-=5;line('Quote: '+q.title,12,true);line('Reference: '+(q.reference||'-')+'   Issued: '+dateLabel(q.date)+'   Valid until: '+dateLabel(q.expiry));line('Status: '+q.status+'   Prepared by: Daniel Ovenden');y-=8;rule();
function tableHeader(){room(45);text('ITEM / DESCRIPTION',42,y,9,true);text('QTY',345,y,9,true);text('UNIT (EX GST)',396,y,9,true);text('TOTAL',505,y,9,true);y-=18;}
tableHeader();for(const item of q.items.filter(i=>(!i.optional||i.selected)&&i.qty>0)){const desc=wrap(item.name,46);const notes=item.note?wrap('Note: '+item.note,88):[];const h=desc.length*14+notes.length*12+27;if(y-h<66){finish();start();tableHeader();}text(String(item.qty),345,y,10);text(money(item.price),396,y,10);text(money(item.price*item.qty),493,y,10,true);for(const l of desc){text(l,42,y,10,true);y-=14;}text(item.sku+(item.optional?' (selected extra)':''),42,y,8,false,'0.45 0.55 0.62');y-=15;for(const l of notes){room(15);text(l,42,y,9);y-=12;}y-=11;}
room(150);rule();const t=totals(q);for(const [label,v] of [['Items',t.items],['Delivery',q.freight],['Site handling',q.handling],['GST (10%)',t.gst]] as const){text(label,340,y,10);text(money(v),493,y,10);y-=19;}y-=5;text('TOTAL INCL. GST',315,y,12,true);text(money(t.total),466,y,14,true,'0.025 0.36 0.61');y-=34;
if(q.po)line('Purchase order: '+q.po,10,true);if(q.instructions)line('Delivery instructions: '+q.instructions);
if(q.acceptedAt){line('TEST ACCEPTANCE RECORDED',11,true);line('Accepted by '+q.acceptedBy+' at '+new Date(q.acceptedAt).toISOString());line('Method: '+q.payment+'. No payment or order created.');}
if(q.items.some(i=>i.optional&&!i.selected)){room(40);line('OPTIONAL EXTRAS - NOT INCLUDED IN TOTAL',10,true);for(const i of q.items.filter(i=>i.optional&&!i.selected))line(i.name+' - '+money(i.price)+' each (ex GST)',9);y-=10;}
room(50);line('QUOTATION TERMS',10,true);line(q.terms,9);y-=10;room(45);text('Open your quotation online (private test preview)',42,y,10,true,'0.025 0.36 0.61');const linkY=y;finish(linkY);
const objs:string[]=[];const add=(s:string)=>{objs.push(s);return objs.length;};add('');add('');const f1=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>');const f2=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>');const kids:number[]=[];for(const p of pages){const stream=add('<< /Length '+p.commands.length+' >>\nstream\n'+p.commands+'endstream');let annotation=0;if(p.linkY)annotation=add(`<< /Type /Annot /Subtype /Link /Rect [42 ${p.linkY-3} 360 ${p.linkY+13}] /Border [0 0 0] /A << /S /URI /URI (${esc(url)}) >> >>`);kids.push(add(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${f1} 0 R /F2 ${f2} 0 R >> >> /Contents ${stream} 0 R ${annotation?'/Annots ['+annotation+' 0 R]':''} >>`));}objs[0]='<< /Type /Catalog /Pages 2 0 R >>';objs[1]='<< /Type /Pages /Count '+kids.length+' /Kids ['+kids.map(i=>i+' 0 R').join(' ')+'] >>';let out='%PDF-1.4\n';const offsets=[0];objs.forEach((o,i)=>{offsets.push(out.length);out+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const xref=out.length;out+='xref\n0 '+(objs.length+1)+'\n0000000000 65535 f \n';for(const offset of offsets.slice(1))out+=String(offset).padStart(10,'0')+' 00000 n \n';out+='trailer\n<< /Size '+(objs.length+1)+' /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF';return new TextEncoder().encode(out);
}
