import {checkoutSchema,checkoutShipment} from './checkout';
import {validDiscount} from './line-pricing';
import {freightNeedsRefresh} from './freight';
import {HAND_UNLOAD_FEE} from './fulfilment';
import {australianStates} from '@/lib/delivery-address';
import {lineKey,type Quote,needsReview,expired,totals,needsPrice} from '@/lib/quote';
import {cleanNote,reanchorBlocks} from './quote-layout';
import {z} from 'zod';
import {declineReasons} from './decline-reasons';
const text=z.string().max(2000);const cents=z.number().int().min(0).max(100000000);const item=z.object({discount:z.object({type:z.enum(['amount','percent']),value:z.number().finite().min(0).max(100000000)}).optional(),productSource:z.literal('exo').optional(),exoDescriptionHtml:z.string().max(40000).optional(),noAutoOptions:z.boolean().optional(),autoOptionFor:z.string().max(100).optional(),autoOptionSource:z.enum(['related','otherskus']).optional(),lineId:z.string().uuid().optional(),sourceSku:z.string().max(100).optional(),adhocId:z.string().uuid().optional(),sku:z.string().min(1).max(100),name:z.string().min(1).max(250),price:cents,standardPrice:cents.optional(),qty:z.number().int().min(0).max(10000),baseQty:z.number().int().min(0).max(10000),optional:z.boolean(),selected:z.boolean(),note:text,image:z.string().max(300).optional(),images:z.array(z.string().max(300)).max(8).optional(),custom:z.boolean().optional(),url:z.string().url().optional()}).refine(validDiscount,'Discount must be 0–100% (up to two decimals), or a dollar amount no greater than the quoted unit price.');
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Enter a valid date');
const fulfilmentMethod=z.enum(['delivery','pickup','own-freight']);
const block=z.object({id:z.string().uuid(),kind:z.enum(['divider','note']),beforeSku:z.string().max(100).nullable(),content:z.array(z.unknown()).refine(v=>JSON.stringify(v).length<=30000,'Keep each note under 30,000 characters.').transform(v=>cleanNote(v))});
const blocks=z.array(block).max(50).default([]).refine(v=>new Set(v.map(b=>b.id)).size===v.length,'Duplicate note or divider.');
const freightEstimate=z.object({fingerprint:z.string().max(20000),carrierCode:z.string().max(100),methodCode:z.string().max(100),label:z.string().max(200),amount:cents,calculatedAt:z.string().datetime()}).nullable().optional();
const fields=z.object({freightEstimate,hubspotContactId:z.string().regex(/^(?:[0-9]{1,30})?$/).optional(),hubspotCompanyId:z.string().regex(/^(?:[0-9]{1,30})?$/).optional(),company:z.string().min(1).max(200),contact:z.string().min(1).max(200),email:z.string().email(),address:z.string().trim().min(1).max(500),suburb:z.string().trim().max(100).default(''),state:z.union([z.enum(australianStates),z.literal('')]).default(''),postcode:z.string().trim().regex(/^(?:[0-9]{4})?$/,'Postcode must contain four digits.').default(''),title:z.string().min(1).max(200),reference:text,vendorNumber:z.string().trim().max(100).default(''),customerTerms:z.string().trim().max(200).default(''),date,expiry:date,fulfilmentMethod:fulfilmentMethod.default('delivery'),hidePickup:z.boolean().default(false),hideOwnFreight:z.boolean().default(false),ownFreightNotes:text.default(''),deliveryNotes:text.default(''),freight:cents,handling:cents,terms:text,items:z.array(item).min(1).max(50),blocks,po:text,instructions:text});

export function applyQuoteAction(current:Quote,body:any):Quote {
const q=structuredClone(current);
if(body.version!==q.version)throw new Error('This quote was updated in another window. Reload it before saving.');const at=new Date().toISOString();let event='';
if(body.action==='save'){
 if(!['Draft','Changes requested'].includes(q.status))throw new Error('Create a revision before editing this quote.');
 const f=fields.parse(body.quote);if((f.hidePickup&&f.fulfilmentMethod==='pickup')||(f.hideOwnFreight&&f.fulfilmentMethod==='own-freight'))f.fulfilmentMethod='delivery';if(f.expiry<f.date)throw new Error('Expiry must be on or after the issue date.');if(f.items.every(i=>i.optional||i.qty===0))throw new Error('Add at least one standard item with a quantity.');f.items=f.items.map(i=>({...i,standardPrice:(i.standardPrice??0)>0?i.standardPrice:i.price}));Object.assign(q,f);event='Quote details saved';
}else if(body.action==='ready'){
 if(!['Draft','Changes requested','Awaiting approval'].includes(q.status))throw new Error('Only a draft or changed quote can be approved.');fields.parse(q);if(freightNeedsRefresh(q))throw new Error('Recalculate freight or confirm the entered amount manually before approval.');if((q.hidePickup&&q.fulfilmentMethod==='pickup')||(q.hideOwnFreight&&q.fulfilmentMethod==='own-freight'))q.fulfilmentMethod='delivery';if(q.items.some(needsPrice))throw new Error('Enter a unit price greater than zero for every product before approval.');if(expired(q))throw new Error('Update the expiry date before approving.');q.blocks=reanchorBlocks({...q,blocks:blocks.parse(q.blocks)},q.items.filter(i=>i.optional||i.qty>0));q.items=q.items.filter(i=>i.optional||i.qty>0).map(i=>({...i,baseQty:i.qty,standardPrice:(i.standardPrice??0)>0?i.standardPrice:i.price}));if(!q.items.some(i=>!i.optional&&i.qty>0))throw new Error('Add at least one standard item.');q.status='Ready';q.snapshots.push({revision:q.revision,at,quote:JSON.parse(JSON.stringify({...q,snapshots:[],events:[]}))});event='Quote approved for customer preview';
}else if(body.action==='request-approval'){
 if(!['Draft','Changes requested'].includes(q.status))throw Error('Save a draft before requesting approval.');fields.parse(q);q.status='Awaiting approval';event='Administrator approval requested';
}else if(body.action==='revise'){
 if(q.status==='Draft')throw new Error('This quote is already a draft.');q.snapshots.push({revision:q.revision,at,quote:JSON.parse(JSON.stringify({...q,snapshots:[],events:[]}))});q.revision++;q.status='Draft';delete q.acceptedAt;delete q.acceptedBy;delete q.payment;event='Revision '+q.revision+' created';
}else if(body.action==='customer'){
 if(q.status!=='Ready'||expired(q))throw new Error('This quote is not available for changes.');const changes=z.array(z.object({lineId:z.string().uuid().optional(),sku:z.string(),qty:z.number().int().min(0).max(10000),selected:z.boolean()})).max(50).parse(body.items);if(new Set(changes.map(lineKey)).size!==changes.length)throw new Error('Duplicate items.');const original=JSON.parse(JSON.stringify({...q,snapshots:[],events:[]}));q.items=q.items.map(i=>{const c=changes.find(x=>lineKey(x)===lineKey(i)&&x.sku===i.sku);return c?{...i,qty:c.qty,selected:c.selected}:i;});q.fulfilmentMethod=fulfilmentMethod.parse(body.fulfilmentMethod??q.fulfilmentMethod??'delivery');if(q.hidePickup&&q.fulfilmentMethod==='pickup')throw new Error('Pickup is not available for this quote. Please select delivery.');if(q.hideOwnFreight&&q.fulfilmentMethod==='own-freight')throw new Error('Own Freight is not available for this quote. Please select another option.');if(body.hasForklift!==undefined)q.handling=z.boolean().parse(body.hasForklift)?0:HAND_UNLOAD_FEE;q.po=text.parse(body.po||'');q.instructions=text.parse(body.instructions||'');if(needsReview(q)){q.snapshots.push({revision:q.revision,at,quote:original});q.revision++;q.status='Changes requested';event='Customer reduced a discounted item quantity; sales approval required';}else{const quantityChanged=q.items.some(i=>i.qty!==current.items.find(old=>lineKey(old)===lineKey(i))?.qty);const kept=q.items.filter(i=>i.optional||i.qty>0);q.blocks=reanchorBlocks(q,kept);q.items=kept.map(i=>({...i,baseQty:i.qty}));event=quantityChanged?'Customer updated quantities without approval; quoted unit prices retained':'Customer saved selections and fulfilment details';}
 if(freightNeedsRefresh(q))event+='; delivery freight refresh required before acceptance';
 if(current.handling!==q.handling)event+='; '+(q.handling===0?'Forklift available for delivery unloading (no site handling fee)':'Hand unload selected ($25.00 ex GST)');
 if((current.fulfilmentMethod??'delivery')!==q.fulfilmentMethod)event+='; '+(q.fulfilmentMethod==='own-freight'?'Own Freight selected (no Verdex freight charge)':q.fulfilmentMethod==='pickup'?'Pickup selected ($35.00 ex GST)':'Delivery selected');
}else if(body.action==='checkout-save'){
 if(q.status!=='Ready'||expired(q)||needsReview(q))throw Error('This quote requires approval or has expired.');
 if(!q.items.some(i=>(!i.optional||i.selected)&&i.qty>0))throw Error('The quote has no selected items.');
 const result=checkoutSchema.safeParse(body.checkout);if(!result.success)throw Error(result.error.issues[0]?.message||'Check your checkout details.');
 const details=result.data;
 if(q.hidePickup&&details.fulfilmentMethod==='pickup')throw Error('Pickup is not available for this quote.');
 if(q.hideOwnFreight&&details.fulfilmentMethod==='own-freight')throw Error('Own Freight is not available for this quote.');
 Object.assign(q,checkoutShipment(q,details));q.checkout=details;q.po=details.purchaseOrder;q.instructions=details.orderComment;
 event='Checkout details saved; no order or payment created'+(freightNeedsRefresh(q)?'; delivery freight refresh required before acceptance':'');
}else if(body.action==='message'){
 const message=z.string().trim().min(1).max(2000).parse(body.message);event=(body.staff?'Sales team: ':'Customer: ')+message;
}else if(body.action==='accept'){
 if(freightNeedsRefresh(q))throw new Error('Delivery freight needs review before accepting this quote.');if(q.status!=='Ready'||expired(q)||needsReview(q))throw new Error('This quote requires approval or has expired.');if(!q.items.some(i=>(!i.optional||i.selected)&&i.qty>0))throw new Error('The quote has no items.');if(!body.agreed)throw new Error('Please confirm that you accept the quote.');q.acceptedBy=z.string().trim().min(2).max(200).parse(body.name);q.po=text.parse(body.po||'');q.payment=z.enum(['checkout','account']).parse(body.payment);if(q.payment==='account'&&!q.po.trim())throw new Error('Enter a purchase order number.');q.acceptedAt=at;q.status='Accepted';event='Test acceptance recorded by '+q.acceptedBy+'; '+(q.payment==='account'?'account request':'checkout payment pending')+' (no order or payment created)';
}else if(body.action==='decline'){
 if(q.status!=='Ready')throw new Error('Only a ready quote can be declined.');const reason=z.enum(declineReasons).safeParse(body.reason);if(!reason.success)throw new Error('Select one reason before declining this quote.');q.status='Declined';event='Customer declined: '+reason.data;
}else throw new Error('Unsupported action.');
if(new Set(q.items.map(i=>lineKey(i).trim().toUpperCase())).size!==q.items.length)throw new Error('Each quote line must have a unique reference.');if(totals(q).total>10000000000)throw new Error('Quote value exceeds the test limit.');q.events.push({at,text:event});q.version++;return q;
}
