import {type Quote,needsReview,expired,totals,needsPrice} from '@/lib/quote';
import {z} from 'zod';
const text=z.string().max(2000);const cents=z.number().int().min(0).max(100000000);const item=z.object({sku:z.string().min(1).max(100),name:z.string().min(1).max(250),price:cents,standardPrice:cents.optional(),qty:z.number().int().min(0).max(10000),baseQty:z.number().int().min(0).max(10000),optional:z.boolean(),selected:z.boolean(),note:text,image:z.string().max(300).optional(),url:z.string().url().optional()});
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Enter a valid date');
const fields=z.object({company:z.string().min(1).max(200),contact:z.string().min(1).max(200),email:z.string().email(),address:z.string().min(1).max(500),title:z.string().min(1).max(200),reference:text,date,expiry:date,freight:cents,handling:cents,terms:text,items:z.array(item).min(1).max(50),po:text,instructions:text});

export function applyQuoteAction(current:Quote,body:any):Quote {
const q=structuredClone(current);
if(body.version!==q.version)throw new Error('This quote was updated in another window. Reload it before saving.');const at=new Date().toISOString();let event='';
if(body.action==='save'){
 if(!['Draft','Changes requested'].includes(q.status))throw new Error('Create a revision before editing this quote.');
 const f=fields.parse(body.quote);if(f.items.some(needsPrice))throw new Error('Enter a unit price greater than zero for every highlighted product before saving.');if(f.expiry<f.date)throw new Error('Expiry must be on or after the issue date.');if(f.items.every(i=>i.optional||i.qty===0))throw new Error('Add at least one standard item with a quantity.');f.items=f.items.map(i=>({...i,standardPrice:(i.standardPrice??0)>0?i.standardPrice:i.price}));Object.assign(q,f);event='Quote details saved';
}else if(body.action==='ready'){
 if(!['Draft','Changes requested'].includes(q.status))throw new Error('Only a draft or changed quote can be approved.');fields.parse(q);if(q.items.some(needsPrice))throw new Error('Enter a unit price greater than zero for every product before approval.');if(expired(q))throw new Error('Update the expiry date before approving.');q.items=q.items.filter(i=>i.optional||i.qty>0).map(i=>({...i,baseQty:i.qty,standardPrice:(i.standardPrice??0)>0?i.standardPrice:i.price}));if(!q.items.some(i=>!i.optional&&i.qty>0))throw new Error('Add at least one standard item.');q.status='Ready';q.snapshots.push({revision:q.revision,at,quote:JSON.parse(JSON.stringify({...q,snapshots:[],events:[]}))});event='Quote approved for customer preview';
}else if(body.action==='revise'){
 if(q.status==='Draft')throw new Error('This quote is already a draft.');q.snapshots.push({revision:q.revision,at,quote:JSON.parse(JSON.stringify({...q,snapshots:[],events:[]}))});q.revision++;q.status='Draft';delete q.acceptedAt;delete q.acceptedBy;delete q.payment;event='Revision '+q.revision+' created';
}else if(body.action==='customer'){
 if(q.status!=='Ready'||expired(q))throw new Error('This quote is not available for changes.');const changes=z.array(z.object({sku:z.string(),qty:z.number().int().min(0).max(10000),selected:z.boolean(),note:text})).max(50).parse(body.items);if(new Set(changes.map(i=>i.sku)).size!==changes.length)throw new Error('Duplicate items.');const original=JSON.parse(JSON.stringify({...q,snapshots:[],events:[]}));q.items=q.items.map(i=>{const c=changes.find(x=>x.sku===i.sku);return c?{...i,qty:c.qty,selected:c.selected,note:c.note}:i;});q.po=text.parse(body.po||'');q.instructions=text.parse(body.instructions||'');if(needsReview(q)){q.snapshots.push({revision:q.revision,at,quote:original});q.revision++;q.status='Changes requested';event='Customer reduced a discounted item quantity; sales approval required';}else{const quantityChanged=q.items.some(i=>i.qty!==current.items.find(old=>old.sku===i.sku)?.qty);q.items=q.items.map(i=>({...i,baseQty:i.qty}));event=quantityChanged?'Customer updated quantities without approval; quoted unit prices and delivery charges retained':'Customer saved selections and delivery details';}
}else if(body.action==='message'){
 const message=z.string().trim().min(1).max(2000).parse(body.message);event=(body.staff?'Sales team: ':'Customer: ')+message;
}else if(body.action==='accept'){
 if(q.status!=='Ready'||expired(q)||needsReview(q))throw new Error('This quote requires approval or has expired.');if(!q.items.some(i=>(!i.optional||i.selected)&&i.qty>0))throw new Error('The quote has no items.');if(!body.agreed)throw new Error('Please confirm that you accept the quote.');q.acceptedBy=z.string().trim().min(2).max(200).parse(body.name);q.po=text.parse(body.po||'');q.payment=z.enum(['checkout','account']).parse(body.payment);if(q.payment==='account'&&!q.po.trim())throw new Error('Enter a purchase order number.');q.acceptedAt=at;q.status='Accepted';event='Test acceptance recorded by '+q.acceptedBy+'; '+(q.payment==='account'?'account request':'Magento checkout pending')+' (no order or payment created)';
}else if(body.action==='decline'){
 if(q.status!=='Ready')throw new Error('Only a ready quote can be declined.');q.status='Declined';event='Customer declined: '+z.string().trim().min(1).max(1000).parse(body.reason);
}else throw new Error('Unsupported action.');
if(new Set(q.items.map(i=>i.sku)).size!==q.items.length)throw new Error('Each SKU must be unique.');if(totals(q).total>10000000000)throw new Error('Quote value exceeds the test limit.');q.events.push({at,text:event});q.version++;return q;
}
