const fs=require('fs'),path=require('path'),ts=require('typescript'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),cache=new Map();
function load(p){p=path.resolve(root,p);if(cache.has(p))return cache.get(p);const e={};cache.set(p,e);new Function('require','exports',ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText)(n=>n.startsWith('@/')?load(n.slice(2)+'.ts'):n.startsWith('.')?load(path.resolve(path.dirname(p),n+'.ts')):require(n),e);return e;}
const {newQuote,totals,money}=load('lib/quote.ts'),{quotePdf}=load('lib/pdf.ts'),{publicPdfImageUrl,pdfImageType,readPdfImage}=load('lib/pdf-images.ts');
const output=process.env.PDF_TEST_OUTPUT||'/workspace/scratch/df17ab7930d5/tmp/pdfs';fs.mkdirSync(output,{recursive:true});
const text=bytes=>{const r=require('child_process').spawnSync('pdftotext',['-','-'],{input:Buffer.from(bytes)});assert.equal(r.status,0);return r.stdout.toString().replace(/\s+/g,' ');};
(async()=>{
 const q={...newQuote(true),number:'VQ-4BE95871',salesperson:{name:'Alex Taylor',email:'alex@example.test',phone:'02 8866 4600'},contact:'Ryan McDougall',email:'test@abc.com.au',suburb:'HEMMANT',state:'QLD',postcode:'4174',date:'2026-09-25',expiry:'2026-10-25',vendorNumber:'ABC1234',customerTerms:'30 DAYS EOM',reference:'',deliveryNotes:'Please call before delivery.',freight:11500,handling:2500,items:[{lineId:'test-product',sku:'V7260K',name:'Louvre Panel Trolley Kit With StorPak Bins',qty:1,baseQty:1,price:108500,optional:false,selected:true,note:'',url:'https://www.verdex.com.au/louvre-square-hole-panel-trolleys'}]};
 const imagePath=path.join(output,'sample-product.png'),images=new Map();if(fs.existsSync(imagePath))images.set('test-product',new Uint8Array(fs.readFileSync(imagePath)));
 const sample=await quotePdf(q,'https://example.invalid/quote/test',images);fs.writeFileSync(path.join(output,'quote-preview.pdf'),sample);
 const sampleText=text(sample);for(const value of [q.number,q.company,q.contact,'Quotation Prepared By: Alex Taylor','Email: alex@example.test','Phone: 02 8866 4600','Vendor Number: ABC1234','Customer terms: 30 DAYS EOM','V7260K',money(totals(q).total),'Approve Quote and Checkout','Bank Account Details','Page 1 of 1'])assert.ok(sampleText.includes(value),value);
 assert.ok(sampleText.includes('Please call before delivery.'));assert.ok(!sampleText.includes('Delivery to '));assert.ok(!sampleText.includes("QUOTATION TERMS"));assert.ok(!sampleText.includes(q.terms));assert.ok(sampleText.includes("Quotation is subject to Verdex's terms and conditions."));assert.ok(sampleText.indexOf("Thank you for your enquiry")<sampleText.indexOf("Quotation is subject"));
 const largeQuote={...q,freight:99397,handling:0,items:[{...q.items[0],price:2685600}]};
 fs.writeFileSync(path.join(output,'quote-large-total.pdf'),await quotePdf(largeQuote,'https://example.invalid/quote/test',images));
 const maxQuote={...q,freight:0,handling:0,items:[{...q.items[0],price:9090909000}]};
 fs.writeFileSync(path.join(output,'quote-max-total.pdf'),await quotePdf(maxQuote,'https://example.invalid/quote/test',images));
 const {PDFDocument}=require('pdf-lib'),doc=await PDFDocument.load(sample);assert.equal(doc.getPageCount(),1);assert.ok(doc.getPage(0).node.Annots().size()>=3);
 const many={...q,items:Array.from({length:50},(_,n)=>({...q.items[0],lineId:'line-'+n,sku:'SKU-'+n,qty:n+1,price:n===0?0:1000+n,note:n===2?'Line note '.repeat(150):'',optional:n>=47,selected:n===47})),blocks:[{id:'divider',kind:'divider',beforeSku:'line-12',content:[]},{id:'note',kind:'note',beforeSku:'line-13',content:[{type:'p',children:[{type:'text',text:'Second delivery address: 5 Example Street, Melbourne VIC 3000'}]}]}],deliveryNotes:'Delivery comments '.repeat(180),instructions:'Delivery instructions that must not appear in the PDF',terms:'Terms and conditions '.repeat(100),customerTerms:'Extended account terms '.repeat(9)};
 const long=await quotePdf(many,'https://example.invalid/quote/long');fs.writeFileSync(path.join(output,'quote-multipage.pdf'),long);const lt=text(long);assert.ok(lt.includes('Delivery comments'));assert.ok(!lt.includes('Delivery instructions that must not appear'));assert.ok(lt.includes('SKU-47'));assert.ok(!lt.includes('SKU-48'));assert.ok(!lt.includes('SKU-49'));assert.ok(lt.includes('Second delivery address'));assert.ok(lt.includes(money(totals(many).total)));assert.ok(!lt.includes('ADDITIONAL OPTIONS')); const pages=(await PDFDocument.load(long)).getPageCount();assert.ok(pages>3);assert.ok(lt.includes('Page '+pages+' of '+pages));
 const empty=await quotePdf({...q,items:[],blocks:[],freight:0,handling:0},'https://example.invalid/quote/empty');assert.ok(text(empty).includes('$0.00'));
 for(const url of ['http://www.verdex.com.au/media/catalog/product/a.jpg','https://127.0.0.1/media/catalog/product/a.jpg','https://www.verdex.com.au:8443/media/catalog/product/a.jpg','https://www.verdex.com.au/admin/a.jpg','https://www.verdex.com.au/media/catalog/product/../../../admin/a.jpg','https://www.verdex.com.au/media/catalog/product/a.jpg?redirect=1'])assert.equal(publicPdfImageUrl(url),null);
 assert.ok(publicPdfImageUrl('https://www.verdex.com.au/media/catalog/product/a.jpg'));assert.equal(pdfImageType(new Uint8Array(30)),null);assert.equal(await readPdfImage(new Response('not an image')),null);
 console.log('PASS: sample layout, exact totals, logo/product images, clickable links, pagination, 50 products, optional exclusions, zero prices, empty quotes, dividers, long notes/terms and bounded image sources.');
 console.log('Preview:',path.join(output,'quote-preview.pdf'),'Multipage:',pages,'pages');
})().catch(e=>{console.error(e);process.exitCode=1;});
